### ISSUE TITLE
اجرا نشدن

### ISSUE THREAD

**Issue by ahadzadeh** [NabiKAZ/instagram-downloader#1]
با سلام
نمیدونم چرا اجرا نمیشه و آیکونش نمایش داده نمشه؟
کسی جدیدا تست کرده ببینه کار میکنه یا نه؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>
مشکل حل شد. صفحه مربوطه رو به شکل پاپ آپ باز نکنید و یکبار صفحه رو رفرش کنید تا به شکل صفحه مستقل باز بشه.

ولی با تغییرات اینستا شاید باز مشکل دیگه ای رخ بده.

پیشنهاد میکنم سرچ کنید و افزونه های مستقل کروم رو هم امتحان کنید همچنین سایتهایی که ابزار آنلاین دارند که تنها آدرس صفحه رو بهش میدید و تمام عکس و فیلم و استوری های پیج رو بهتون میده.
